#!/usr/bin/env fish
# Make sure fish is installed on target system

pushd $DOTFILES
for item in *
    if [ -d $item ]
        echo "Unstowing --> " $item
        stow -D $item
    else
        echo "Ignoring file --> " $item
    end
end
popd

echo "Dotfiles cleaned. Do you want to restart your shell to see changes? (y/n)"
read confirm
if [ "$confirm" = "y" ]
    echo "Restarting..."
    exec {$SHELL}
end
