#!/usr/bin/env bash

# Things I like to have
PACKAGES="git zsh tmux stow neofetch"
# Stuff that other tools need to build
PACKAGES+=" curl wget pkg-config libssl-dev build-essential unzip make"
# Other envs
PACKAGES+=" npm python3-pip python3-venv gcc"

PIP_PACKAGES="virtualenv"

CRATES="aichat bat du-dust eza gitui ripgrep cargo-update bob-nvim zellij tealdeer zr fd-find skim zoxide"

echo
echo "Packages to install: $PACKAGES"
read -rp "?Install apt/brew/yum packages? (y/n)? " choice
if [[ $choice =~ ^[Yy]$ ]]; then
  if command -v brew >/dev/null 2>&1; then
    brew update
    brew upgrade
    brew install "$PACKAGES"
  elif command -v apt >/dev/null 2>&1; then
    sudo apt update
    sudo apt upgrade -y
    sudo apt install -y "$PACKAGES"
  elif command -v yum >/dev/null 2>&1; then
    sudo yum update
    sudo yum upgrade -y
    sudo yum install -y "$PACKAGES"
  else
    echo "No supported package manager found"
  fi
fi

# Rust installation - from https://rustup.rs/
echo
if command -v cargo >/dev/null 2>&1; then
  echo "Crates to install: cargo-binstall $CRATES"
  read -rp "?Install cargo crates? Cargo-binstall will be compiled then used to install the rest (y/n)? " choice
  if [[ $choice =~ ^[Yy]$ ]]; then
    cargo install cargo-binstall
    cargo binstall --no-confirm "$CRATES"
  fi
else
  read -rp "?Install rustup? (y/n)? " choice
  if [[ $choice =~ ^[Yy]$ ]]; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    echo "You will need to restart your shell then run this script again to install Cargo crates..."
  fi
fi

echo
if command -v python3 >/dev/null 2>&1; then
  echo "Pip packages to install: $PIP_PACKAGES"
  read -rp "?Install Pip packages? (y/n)? " choice
  if [[ $choice =~ ^[Yy]$ ]]; then
    python3 -m pip install $PIP_PACKAGES
  fi
else 
  echo "Python3 not found, can't install pip packages"
fi

# Neovim from apt is out of date, bob can pull the latest versions
echo
read -rp "?Install neovim using bob? (y/n)? " choice
if [[ $choice =~ ^[Yy]$ ]]; then
  bob use stable
fi

echo
if [[ $SHELL != */zsh ]]; then
  read -rp "?Set zsh as default shell (y/n)? " choice
  if [[ $choice =~ ^[Yy]$ ]]; then
    chsh -s "$(command -v zsh)"
    echo "You may need a terminal/system reboot for this change to stick."
  fi
else
  echo "zsh is already default, nothing to do here..."
fi

echo "Done!"
