#!/bin/bash

PACKAGES="git zsh curl neovim pkg-config libssl-dev stow"

CRATES="aichat bat du-dust exa gitui ripgrep cargo-update"


if command -v brew >/dev/null 2>&1; then
  brew install $PACKAGES
elif command -v apt >/dev/null 2>&1; then
  sudo apt install -y $PACKAGES
fi

# Rust installation - from https://rustup.rs/
if command -v cargo >/dev/null 2>&1; then
  read -p "?Install cargo crates? This could take awhile (y/n)? " choice
  if [[ $choice =~ ^[Yy]$ ]]; then
    cargo install cargo-binstall
    cargo binstall $CRATES
  fi
else
  read -p "?Install rustup? (y/n)? " choice
  if [[ $choice =~ ^[Yy]$ ]]; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  fi
fi

# AstroNvim install from - https://github.com/AstroNvim/AstroNvim
read -p "?Install AstroNvim config? (y/n)? " choice
if [[ $choice =~ ^[Yy]$ ]]; then
  mv ~/.config/nvim ~/.config/nvim.bak
  mv ~/.local/share/nvim ~/.local/share/nvim.bak
  git clone --depth 1 https://github.com/AstroNvim/AstroNvim ~/.config/nvim
fi

if [[ $SHELL != */zsh ]]; then
  read -p "?Set zsh as default shell (y/n)? " choice
  if [[ $choice =~ ^[Yy]$ ]]; then
    chsh -s "$(command -v zsh)"
    echo "You may need a terminal/system reboot for this change to stick."
  fi
else
  echo "zsh is already default, nothing to do here..."
fi

echo "Done!"
